FORMAT: 1A
HOST: http://localhost:9090

# chunge-shudong

Shudong Mock Server API

Use jwt, so no token in request params/form.

Response Code and msg:
Code | msg      |
---- | -------  | 
200  | OK            | 
201  | Created       | 
401  | Unauthorized  |
403  | Forbidden     |
409  | Conflict      |
500  | InternalServerError      |


# Group User
This section groups User resources.

## Login [/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "example@mail2.sysu.edu.cn",
            "password": "pass"
        }

+ Response 200 (application/json)

    + Headers

            Access-Control-Expose-Headers: Authorization
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

    + Body

            {
                "msg": "OK",
                "data": {
                    "userId": 1
                }
            }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }

## Logout [/logout]

### Logout [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

    + Body

            {
                "userId": 1
            }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {}
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }

## Register [/users]

### Register New User [POST]

+ Request (application/json)

        {
            "email": "example@mail2.sysu.edu.cn",
            "password": "pass"
        }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "userId": 1
            }
        }

+ Response 409 (application/json)

        {
            "msg": "Conflict",
            "data": {}
        }


## Change Password [/users/password]

### Change Password [PATCH]

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

    + Body

            {
                "oldPassword": "pass",
                "newPassword": "123"
            }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {}
        }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }


## User Operations [/users/{userId}]

+ Parameters
    + userId: `1` (number, required) - The ID of the user.

### Retrieve User Info [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "user": {
                    "userId": 1
                },
                "likePosts": [
                    {
                        "postId": 1,
                        "author": "元首",
                        "title" : "post-title-1",
                        "content": "post-content-1",
                        "likeCount": 666,
                        "commentCount": 777
                    },
                    {
                        "postId": 2,
                        "author": "春哥",
                        "title" : "post-title-2",
                        "content": "post-content-2",
                        "likeCount": 0,
                        "commentCount": 3
                    }
                ],
                "likeComments": [
                    {
                        "commentId": 5,
                        "author": "德国BOY",
                        "relatedPostId": 1,
                        "content":"comment(1) on postId=1",
                        "likeCount": 5
                    },
                    {
                        "commentId": 8,
                        "author": "非凡哥",
                        "relatedPostId": 1,
                        "content":"comment(2) on postId=1",
                        "likeCount": 0
                    }
                ],
                "starPosts": [
                    {
                        "postId": 1,
                        "author": "元首",
                        "title" : "post-title-1",
                        "content": "post-content-1",
                        "likeCount": 666,
                        "commentCount": 777
                    },
                    {
                        "postId": 2,
                        "author": "春哥",
                        "title" : "post-title-2",
                        "content": "post-content-2",
                        "likeCount": 0,
                        "commentCount": 3
                    }
                ],
                "starComments": [
                    {
                        "commentId": 5,
                        "author": "德国BOY",
                        "relatedPostId": 1,
                        "content":"comment(1) on postId=1",
                        "likeCount": 5
                    },
                    {
                        "commentId": 8,
                        "author": "非凡哥",
                        "relatedPostId": 1,
                        "content":"comment(2) on postId=1",
                        "likeCount": 0
                    }
                ]
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }

# Group AuthCode

## Gen Auth Code [/reset_password/authcode]

### Gen Auth Code [POST]

+ Request (application/json)

        {
            "email": "example@mail2.sysu.edu.cn"
        }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "authCode": "123456"
            }
        }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }

# Group Password

## Reset Password [/reset_password]

### Reset Password [PATCH]

+ Request (application/json)

        {
            "email": "example@mail2.sysu.edu.cn",
            "authCode": "123456",
            "newPassword":"123"
        }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {}
        }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }


# Group Post
This section groups Post resources.

## Post Collection [/posts?limit={limitNum}&offset={offset}&categoryName={categoryName}]

+ Parameters
    + limitNum: `10` (number, optional) - Limitation of the number of the posts.
    + offset: `10` (number, optional) - The start position of the results in the post list.
    + categoryName: `category-Name-1` (string, optional) - Name of the category where the posts returned must belong.

### Get recent posts [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "posts": [
                    {
                        "postId": 1,
                        "author": "元首",
                        "title" : "post-title-1",
                        "content": "post-content-1",
                        "categoryName": "category-Name-1",
                        "publishDate": "2018-06-06T22:05:36+08:00",
                        "likeCount": 666,
                        "commentCount": 777
                    },
                    {
                        "postId": 2,
                        "author": "春哥",
                        "title" : "post-title-2",
                        "content": "post-content-2",
                        "categoryName": "category-Name-1",
                        "publishDate": "2018-06-06T22:05:36+08:00",
                        "likeCount": 0,
                        "commentCount": 3
                    },
                    {
                        "postId": 3,
                        "author": "带带大师兄",
                        "title" : "post-title-3",
                        "content": "post-content-3",
                        "categoryName": "category-Name-1",
                        "publishDate": "2018-06-06T22:05:36+08:00",
                        "likeCount": 23,
                        "commentCount": 0
                    }
                ]
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }
## Post Creation [/posts]

### Create a new post [POST]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

    + Body

            {
                "post" : {
                    "categoryName": "Category-1 (init)",
                    "title": "new-post-title",
                    "content": "new post title content"
                }
            }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "post": {
                    "postId": 1,
                    "author": "元首",
                    "title": "new-post-title",
                    "content": "new post title content",
                    "categoryName": "category-Name-1",
                    "publishDate": "2018-06-06T22:05:36+08:00",
                    "likeCount": 0,
                    "commentCount": 0
                }
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }


## Get and Delete Post [/posts/{postId}]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.

### Get a specific post [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg":"OK",
            "data": {
                    "post": {
                        "postId": 1,
                        "author": "元首",
                        "title": "post-title-1",
                        "content": "post-content-1",
                        "categoryName": "category-Name-1",
                        "publishDate": "2018-06-06T22:05:36+08:00",
                        "likeCount": 666,
                        "commentCount": 777
                    }
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }


### Delete a post [DELETE]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {}
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }


## Share a post [/posts/{postId}/share]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.

### Share a post [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "currentUserShared": true,
                "currentPostSharedCount": 20
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }


## Category Names [/posts/categories]

### Get All Category Names [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0


+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "categoryNames": [
                    "category-Name-1",
                    "category-Name-2"
                ]
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }
        

# Group Comment
This section groups Comment resources.

## Comment Collection and Creation [/posts/{postId}/comments]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.

### Get comments pertaining to specific post [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg":"OK",
            "data": {
                "comments": [
                    {
                        "commentId": 5,
                        "author": "德国BOY",
                        "relatedPostId": 1,
                        "content":"comment(1) on postId=1",
                        "publishDate": "2018-06-06T22:05:36+08:00",
                        "likeCount": 5
                    },
                    {
                        "commentId": 8,
                        "author": "非凡哥",
                        "relatedPostId": 1,
                        "content":"comment(2) on postId=1",
                        "publishDate": "2018-06-06T22:05:36+08:00",
                        "likeCount": 0
                    }
                ]
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }

### Comment on a post [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

    + Body

            {
                "comment": {
                    "content": "new comment on postId=1"
                }
            }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "comment": {
                    "commentId": 9,
                    "author": "new comment author",
                    "relatedPostId": 1,
                    "content": "new comment on postId=1",
                    "publishDate": "2018-06-06T22:05:36+08:00",
                    "likeCount": 0
                }
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }

## Comment [/posts/{postId}/comments/{commentId}]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.
    + commentId: `1` (number, required) - The ID of the comment.

### Delete a comment [DELETE]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {}
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }

+ Response 403 (application/json)

        {
            "msg": "Forbidden",
            "data": {}
        }


# Group Like/Unlike
This section groups Like/Unlike resources.

## Like/Un-like a post [/posts/{postId}/like]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.

### Like/Un-like a post [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                    "currentUserLike": true,
                    "currentLikeCount": 10
                }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }


## Like/Un-like a comment [/posts/{postId}/comments/{commentId}/like]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.
    + commentId: `1` (number, required) - The ID of the comment.

### Like/Un-like a comment [GET]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                    "currentUserLike": true,
                    "currentLikeCount": 7
                }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }


# Group Report
This section groups Report resources.

## Report a post [/posts/{postId}/report]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.

### Report a post [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

    + Body

            {
                "reason": "report reason text string"
            }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {}
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }


## Report a comment [/posts/{postId}/comments/{commentId}/report]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.
    + commentId: `1` (number, required) - The ID of the comment.

### Report a comment [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

    + Body

            {
                "reason": "report reason text string"
            }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {}
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }


# Group Star/Unstar
This section groups Star/Unstar resources.

## Star/Unstar a post [/posts/{postId}/star]

+ Parameters
    + postId: `1` (number, required) - The ID of the post.

### Star/Unstar a post [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOnsiZXhwIjoxNTI3ODczNzg5fSwiaWQiOjF9.43YDbJruw6fcxm6GTlTq9iee9n43vst0uhnewqSq7M0

+ Response 200 (application/json)

        {
            "msg": "OK",
            "data": {
                "currentUserStarred": true
            }
        }

+ Response 401 (application/json)

        {
            "msg": "Unauthorized",
            "data": {}
        }
